#!/bin/bash

input_file=$1

filename="$(basename "${input_file}" .svg)"

cairosvg $input_file -o out1.pdf

# Crop
pdfcrop --margins 5 out1.pdf out.pdf

rm out1.pdf

# PNG, 450 ppi
pdftoppm -png -r 450 out.pdf $filename

# remove '-1' that pdftoppm creates
mv $filename-1.png $filename.png

# remove residual file
rm out.pdf

